name: Auto Upgrade OneUptime

on:
  schedule:
    - cron: '0 3 * * 1'  # ทุกวันจันทร์ เวลา 03:00 UTC (10:00 เวลาไทย)
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > kubeconfig.yaml

      - name: Set KUBECONFIG env
        run: echo "KUBECONFIG=$PWD/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Helm Upgrade OneUptime
        run: |
          helm repo add oneuptime https://helm-chart.oneuptime.com
          helm repo update
          helm upgrade --install oneuptime oneuptime/oneuptime \
            -n oneuptime \
            -f helm-values/production-values.yaml
